### ISSUE TITLE
Lastline connector logs do not indicate trouble with invalid credentials

### ISSUE THREAD

**Issue by sjones-github** [carbonblack/cb-lastline-connector#1]
Logs show good connection to lastline analysis server.  No indication the access key and api token were not acceptable.

sqlite3 query provides amplifying information:
291617757D108D10AB9E2DEDD401A60A|2015-12-14 17:59:22.214944|2015-12-14 17:59:18.001032|2015-12-14 18:01:22.101453||0|10|API error: Analysis API error (104): Invalid Credentials||0||||0|1

**Comment by jgarman** [comment]
The binary detonation integrations should log error conditions; the fix has been committed to the cb-integrations repository and will be included as part of the next release of the binary detonation connectors coming by the end of this week. Thanks for the report!

**Comment by jgarman** [comment]
Closing for now. @sjones-github if you are still having issues with this please re-open the issue. Thanks!
