### ISSUE TITLE
Old reports never age out, and the score never gets updated from Lastline

### ISSUE THREAD

**Issue by dbrouss** [carbonblack/cb-lastline-connector#2]
The integrations should have a way to age out old reports like the FireEye integration has.  This could be controlled by an option in the configuration file, or a static setting.  Also, scores change, sometimes drastically (usually down).  A rescan is really needed like CB does with VirusTotal.

**Comment by jgarman** [comment]
Thanks for the report @dbrouss - we don't currently have a way to age those reports and update them on a periodic basis. Will keep this open as an enhancement request.
