### ISSUE TITLE
CB R lastline connector 'view on lastline' link directing to incorrect URL

### ISSUE THREAD

**Issue by erikconnor** [carbonblack/cb-lastline-connector#5]
When clicking the "View on Lastline" link in CBR they are getting sent to https://user.lastline.customerdomain/malscape/#/task/<ID>. 

They say the correct URL should be https://user.lastline.customerdomain/portal#/analyst/task/<ID>

**Comment by 0xpwntester** [comment]
Being trying to solve this with no luck so far. I am not finding where to change this please help. I looked at files in this path /usr/share/cb/integrations/lastline with no luck so far. my 2 options now is either to edit the binary or modify the sqlite database. Please let me know where this parameter stored or issue an update. it is affecting a lot of clients

**Comment by 0xpwntester** [comment]
Please commit the pull request by  @jbmfg
